Add Split to existing landscape research
open-feature/spec pull request #16
Opened 2022-03-08 22:27 UTC by beeme1mr

2022-03-08 22:41 UTC, oleg-nenashev approved these changes

2022-03-08 22:41 UTC, merged

2022-03-08 23:52 UTC, patricioe requested changes

2022-03-08 23:52 UTC, patricioe commented on research/existing-landscape.md
> +  const treatment = client.getTreatment("test-user", "test-feature");
You may want to show both calls. This one and the overloaded that that includes custom user attributes.

2022-03-08 23:52 UTC, patricioe commented on research/existing-landscape.md
> +Evaluator](https://help.split.io/hc/en-us/articles/360020037072-Split-Evaluator)
and also a Proxy/Relay is available.

2022-03-09 07:28 UTC, oleg-nenashev commented
Sorry for merging too early @patricioe. We can address it in a follow-up PR, cc @beeme1mr