Use "Attributes" over "Context"
open-feature/spec pull request #34
Opened 2022-04-14 20:26 UTC by toddbaert

As mentioned in the meeting, this avoids some overload and logical terminology clashes, and I believe maps more specifically to the feature-flags use-case than "context".

Also added a blurb about intent to use implicit state storage mechanisms to propagate attributes.

2022-04-15 07:03 UTC, oleg-nenashev approved these changes

2022-04-15 14:12 UTC, moredip commented
Personally I prefer the word context, although I do agree that there are some naming conflicts here - `context` is on of those words that gets used frequently.

I like context because it captures a bit more of the semantics - which path to go down at run time is a decision that can vary at runtime depending on the *context*. "Attributes" has less semantic meaning for me. Also these values are usually pulled from a request context of some kind (at least for server-side flags), so there is a nice conceptual parallel there.

2022-04-18 14:48 UTC, moredip commented
Perhaps we could disambiguate a bit with a more specific name: `FlagDecisionContext` or `FlagEvaluationContext` or similar

2022-04-18 17:38 UTC, toddbaert commented
@moredip I force-pushed an update. I've changed `Context` to `Evaluation Context`. We use `EvaluationDetails` as well in a few other places in the SDK research typings - so I think in general, it seems "Evaluation" is a good way to denote objects related to, and impacting the evaluation of flags.

I also think `HookContext` is pretty distinct from `EvaluationContext`, so it largely clears that up.

Let me know your thoughts... of course we could go with `FlagEvaluationContext` but I think if we always include "Flag" it's going to feel redundant.

2022-04-19 15:05 UTC, moredip requested changes

2022-04-19 16:41 UTC, toddbaert commented on glossary.md
> +  - [Attributes](#attributes)
Yes! Nice catch, thanks. Updated, squashed, force-pushed.

2022-04-19 19:32 UTC, merged